// Datos prellenados para solicitudes existentes
export const datosExistentes: Record<string, any> = {
  'SOL-2024-001': {
    descripcionNecesidad: 'Se requiere contratar servicios de consultoría especializada en gestión empresarial para el desarrollo de estrategias de atracción de inversión extranjera. El proyecto busca fortalecer las capacidades institucionales y mejorar los procesos de relacionamiento con inversionistas potenciales.',
    objeto: 'Servicios de consultoría especializada en gestión empresarial',
    valorEstimado: '45000000',
    modalidad: 'Invitación',
    justificacionCD: 'Por tratarse de un servicio especializado que requiere evaluación técnica y económica de múltiples propuestas, se selecciona la modalidad de invitación pública para garantizar transparencia y obtener las mejores condiciones para la entidad.',
    fechaEstimadaSolicitud: '2026-02-20',
    fechaEstimadaRecepcion: '2026-03-05',
    lugarEjecucion: 'Bogotá D.C., Colombia',
    efectoEstimarPresupuesto: 'Centro de Costos: CC-001 - Atracción de Inversión | Proyecto: PI-2024-015',
    formaPago: 'Dos pagos: 50% contra entrega de informe parcial, 50% contra entrega de informe final',
    plazoEjecucionDesde: '2026-03-10',
    plazoEjecucionHasta: '2026-09-10',
    supervision: 'Juan Díaz - Líder de Proyecto',
    entregables: '1. Diagnóstico inicial\n2. Plan estratégico de atracción de inversión\n3. Manual de procedimientos\n4. Informe final con recomendaciones',
    riesgos: 'Riesgo de incumplimiento en cronograma, riesgo de calidad del servicio, riesgo contractual',
    criteriosAmbientales: 'No aplica para servicios de consultoría',
    criteriosSST: 'Cumplimiento de normativa SST para trabajo en oficina',
    conclusiones: 'La contratación de estos servicios es fundamental para fortalecer las capacidades institucionales y cumplir con los objetivos estratégicos de atracción de inversión extranjera.',
    proponentes: [
      {
        nombreProveedor: 'Consultores ABC S.A.S.',
        datosContacto: 'contacto@consultoresabc.com - Tel: 310 234 5678',
        requisitosTecnicos: 'Experiencia mínima 5 años en consultoría empresarial',
        experiencia: '8 años en proyectos similares',
        criteriosHabilitantes: 'RUT, Cámara de Comercio vigente, Referencias',
        valorImpuestos: '$45.000.000',
        observaciones: 'Propuesta técnica y económica completa'
      },
      {
        nombreProveedor: 'Inversión Global Ltda.',
        datosContacto: 'info@inversionglobal.co - Tel: 320 345 6789',
        requisitosTecnicos: 'Certificación ISO 9001',
        experiencia: '10 años en sector público',
        criteriosHabilitantes: 'Documentación completa',
        valorImpuestos: '$42.500.000',
        observaciones: 'Mejor oferta económica'
      },
      {
        nombreProveedor: 'Asesores Estratégicos S.A.',
        datosContacto: 'ventas@asesores.com - Tel: 315 456 7890',
        requisitosTecnicos: 'Equipo multidisciplinario',
        experiencia: '6 años',
        criteriosHabilitantes: 'Cumple requisitos',
        valorImpuestos: '$47.000.000',
        observaciones: 'Propuesta técnica destacada'
      },
    ],
  },
  'SOL-2024-002': {
    descripcionNecesidad: 'Es necesario adquirir equipos de cómputo de última generación para el área administrativa con el fin de mejorar la productividad y eficiencia en las labores diarias. Los equipos actuales presentan obsolescencia tecnológica y requieren reemplazo inmediato.',
    objeto: 'Adquisición de equipos de cómputo para el área administrativa',
    valorEstimado: '28500000',
    modalidad: 'Directa',
    justificacionCD: 'Se justifica la modalidad directa considerando que el valor estimado se encuentra dentro de los límites permitidos y existe urgencia en la adquisición para no afectar la operación normal de las actividades administrativas.',
    fechaComite: '2026-02-01',
    modalidadSeleccion: 'Contratación directa por valor',
    lugarEjecucion: 'Bogotá D.C., Colombia',
    efectoEstimarPresupuesto: 'Centro de Costos: CC-002 - Tecnología | Proyecto: PI-2024-008',
    formaPago: 'Pago único contra entrega a satisfacción',
    plazoEjecucionDesde: '2026-02-15',
    plazoEjecucionHasta: '2026-03-15',
    supervision: 'María García - Coordinadora de Tecnología',
    entregables: '15 equipos de cómputo portátiles con especificaciones técnicas mínimas requeridas, licencias de software, garantía de 1 año',
    riesgos: 'Riesgo de disponibilidad de equipos, riesgo de incumplimiento de especificaciones técnicas',
    criteriosAmbientales: 'Equipos con certificación Energy Star',
    criteriosSST: 'No aplica',
  },
  'SOL-2024-003': {
    descripcionNecesidad: 'Se requiere contratar servicios de mantenimiento preventivo y correctivo de las instalaciones para garantizar el adecuado funcionamiento de las áreas de trabajo y cumplir con las normas de seguridad y salud en el trabajo.',
    objeto: 'Mantenimiento preventivo y correctivo de instalaciones',
    valorEstimado: '15000000',
    modalidad: 'Directa',
    justificacionCD: 'La modalidad directa se justifica por el valor de la contratación y la necesidad de continuidad en el servicio de mantenimiento de las instalaciones.',
    fechaComite: '2026-01-25',
    modalidadSeleccion: 'Contratación directa',
    lugarEjecucion: 'Bogotá D.C., Colombia',
    efectoEstimarPresupuesto: 'Centro de Costos: CC-003 - Operaciones | Presupuesto de Funcionamiento 2026',
    formaPago: 'Pagos mensuales vencidos contra certificación de cumplimiento',
    plazoEjecucionDesde: '2026-02-01',
    plazoEjecucionHasta: '2027-01-31',
    supervision: 'Pedro Martínez - Coordinador de Operaciones',
    entregables: 'Informes mensuales de mantenimiento, bitácoras de servicio, plan de mantenimiento preventivo',
    riesgos: 'Riesgo de interrupción del servicio, riesgo de accidentes laborales',
    criteriosAmbientales: 'Uso de productos biodegradables, manejo adecuado de residuos',
    criteriosSST: 'Cumplimiento estricto de normas SST, personal con certificación en trabajo en alturas',
  },
};
